name: Homologation Pipeline

on:
  push:
    branches:
      - homologation

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: "21"

      - name: Install Xvfb
        run: sudo apt-get install -y xvfb

      - name: Run Xvfb
        run: |
          Xvfb :99 -screen 0 1024x768x16 &
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Build with Maven
        env:
          DISPLAY: :99
        run: mvn clean install

      - name: Run Unit and Smoke Tests
        env:
          DISPLAY: :99
        run: mvn test
