name: Java CI with Maven

on:
  push:
    branches:
    - "master"
    - "jpa"
  pull_request:
    branches:
    - "master"
    - "jpa"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Create dotenv File
      run: |
          touch /home/runner/work/even4/even4/.env
          echo DB_URL="${{ secrets.DB_URL_DEFAULT }}" >> /home/runner/work/even4/even4/.env
          echo DB_USER="${{ secrets.DB_USER }}" >> /home/runner/work/even4/even4/.env
          echo DB_PASSWORD="${{ secrets.DB_PASSWORD }}" >> /home/runner/work/even4/even4/.env
          cat /home/runner/work/even4/even4/.env

    - name: Build with Maven
      run: mvn clean package

    - name: Save JAR as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: even4-21.jar
        path: target/even4-21.jar
