name: Java CI with Maven

on:
  push:
    branches:
      - "jpa-security"
  pull_request:
    branches:
      - "jpa-security"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Create dotenv File
        run: |
          touch /home/runner/work/even4/even4/.env
          echo DB_URL="${{ secrets.DB_URL }}" >> /home/runner/work/even4/even4/.env
          echo DB_USER="${{ secrets.DB_USER }}" >> /home/runner/work/even4/even4/.env
          echo DB_PASSWORD="${{ secrets.DB_PASSWORD }}" >> /home/runner/work/even4/even4/.env
          cat /home/runner/work/even4/even4/.env

      - name: Build with Maven
        run: mvn clean package

      - name: Save JAR as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: even4-21.jar
          path: target/even4-21.jar

      - name: Create Tag
        run: |
          TAG_NAME="v1.0-${GITHUB_SHA}"
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: target/even4-21.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
